name: Actions Workflow
on:
  push:
    # branches-ignore:
    #   - ""
    branches:
      - main
      - 'feature/*' # matches feature/featA, feature/featB
                    # doesn't match feature/feat/a
      - 'feature/**'
      - '!feature/featC' # ignore this branch
    tags:
      - v1.*
    paths:
      - '**.js'
  # repository_dispatch:
    # types: [build]
  # schedule:
  #   - cron: "1 * * * *"
  # push:
  # pull_request:
    # types: [closed, assigned, opened, reopened]
jobs: 
  runs-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          # git clone git@github:$GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA
      - name: Checkout 
        uses: actions/checkout@v1
      - name: List files
        run: |
          pwd
          ls
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Yoset
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"